default:
	cp FBSession.m		../ShareKit/Submodules/facebook-ios-sdk/src
	cp SHKTwitter.m		../ShareKit/Classes/ShareKit/Sharers/Services/Twitter
	cp SHKFacebook.h	../ShareKit/Classes/ShareKit/Sharers/Services/Facebook